services:
  postgres:
    image: postgres:15-alpine
    container_name: primeacc_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: primeacc
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: primeacc_redis
    ports:
      - "6380:6379"

volumes:
  postgres_data:
